Set Shell "zsh"
Set Width 1200
Set Height 400
Set Theme "Catppuccin Mocha"
Set FontSize 16
Set Padding 20
Set TypingSpeed 40ms

Output gifs/trust-attest-check-revoked.gif

Hide
Type "export PS1='user@bray:bray $ '"
Enter
Type "alias claude=./site/demos/bray-demo.sh"
Enter
Type "clear"
Enter
Sleep 0.5s
Show

Type "claude -p 'Use trust-attest-check-revoked to check if any attestations for npub180cvv07tjdrrgpa0j7j7tmnyl2yr6yr7l8j4s3evf6u64th6gkwsyjh6w6 have been revoked'"
Enter
Sleep 25s
